jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\\n\\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "password"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 0
  nodes:
    - permanent:
        name: "terraform"
        remoteFS: "/home/jenkins"
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"
    - permanent:
        name: "cloud-image"
        remoteFS: "/home/jenkins"
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"
    